/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accounts: () => import('#controllers/accounts_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Home: () => import('#controllers/home_controller'),
  Users: () => import('#controllers/users_controller'),
}
