/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
}
