/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'initialBalance', 'name', 'type', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare initialBalance: string
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class CategorySchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = CategorySchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class TransactionSchema extends BaseModel {
  static $columns = ['accountId', 'amount', 'categoryId', 'createdAt', 'description', 'destinationAccountId', 'id', 'transactionDate', 'type', 'updatedAt'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare accountId: bigint | number
  @column()
  declare amount: string
  @column()
  declare categoryId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare destinationAccountId: bigint | number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.date()
  declare transactionDate: DateTime
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
